server:
  port: 7778

spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://pg:5432/audio_events
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://sd:7777/eureka/

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
    ttl_ms: 1200000 # 20 min
