server:
  port: 7779

spring:
  application:
    name: backend
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  #  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:postgresql://pg:5432/audio_events
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://sd:7777/eureka/

s3:
  url: http://minio:9000
  bucket: audio
  user: user
  password: password
