server:
  port: 7779

spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/audio_events
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka/

s3:
  url: http://localhost:9000
  bucket: audio
  user: user
  password: password
