server:
  port: 7777

eureka:
  instance:
    hostname: sd
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${EUREKA_INSTANCE_HOSTNAME:sd}:${server.port}/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info